### ISSUE TITLE
Inconsistent formatting of timestamps (bis)

### ISSUE THREAD

**Issue by aldur** [ripple/rippled-historical-database#124]
(Similar in some ways to #89)

A request to get all the validators returns the following data:

```bash
$ curl https://data.ripple.com/v2/network/validators | jq
# ...
    {
      "domain_state": "AccountDomainNotFound",
      "last_datetime": "2016-04-20T20:07:02.105Z",
      "validation_public_key": "n9MqYNiCydizzjMZCWpXbvQgQbjhLdw945iZ2cR52ifL6YLLhbYa"
    }
# ...
```

The `last_datetime` field does not respect the conventions specified in https://github.com/ripple/rippled-historical-database#timestamps, since it contains the milliseconds after the period (?).

**Comment by shekenahglory** [comment]
This is because in this case, we get multiple reports of validations per second, so we need to include milliseconds
