### ISSUE TITLE
Pagination markers not supplied when specifying CSV format

### ISSUE THREAD

**Issue by professorhantzen** [ripple/rippled-historical-database#131]
A workaround - that unfortunately calls the server twice - is to query the set in JSON, retrieve all the markers form the responses, and then repeat the queries in CSV format specifying the markers returned form the JSON requests.

Could the marker for CSV format be included, say, as the first entry of an additional column "marker" (perhaps always the final column)?

**Comment by shekenahglory** [comment]
the marker is there actually - its in the header though, not the body. https://ripple.com/build/data-api-v2/#pagination

**Comment by professorhantzen** [comment]
Aha! Thank you! My bad.
