### ISSUE TITLE
Clamping down on size of database, purging old history

### ISSUE THREAD

**Issue by njmurarka** [ripple/rippled-historical-database#134]
Hello. I was unable to find any instructions on how to manage the data in HBASE so we can keep some control on database growth. 

Is there a script or configuration directive that manages this? I'd prefer to be pro-active about ensuring the database does not grow without bounds.

Please advise.

Thanks.

**Comment by scratch28** [comment]
Unfortunately we do not plan to purge any of the data from our system
From the hbase CLI you can deleteall function that you can script to delete your range of data based on keys
