### ISSUE TITLE
Get Account Reports result omits "currency" field

### ISSUE THREAD

**Issue by professorhantzen** [ripple/rippled-historical-database#135]
The following example api call is supplied in the docs:

https://github.com/ripple/rippled-historical-database#example-45

When copying and pasting the example call verbatim, the call works, but the "currency" field is omitted from the response.  (In the example, the currency field is included in the response.)

**Comment by professorhantzen** [comment]
TBC, this happens for any instance of this call I've tried (not just the document example).

Also, I'm not super familiar with the codebase (or hbase) so apologies if this is a red herring.  But looking around, I wondered is the currency field omitted in the case of getAggregateAccountPayments because it might not be explicitly declared as an option for retrieval?  Somewhere here, or up the line:

https://github.com/ripple/rippled-historical-database/blob/develop/lib/hbase/hbase-thrift/data.js#L350-L404

**Comment by professorhantzen** [comment]
@shekenahglory

**Comment by shekenahglory** [comment]
fixed
