### ISSUE TITLE
data.ripple.com/v2/accounts/?reduce=true returns diffrent numbers

### ISSUE THREAD

**Issue by ihomp** [ripple/rippled-historical-database#137]
I had such an issue before already, but it was fixed and was stable for a while.
Now it's happening again, though not so often as last time. 

<img width="375" alt="1" src="https://cloud.githubusercontent.com/assets/19390499/24575904/33d9bad6-16b2-11e7-8cad-cb8d8a18202f.png">
<img width="374" alt="2" src="https://cloud.githubusercontent.com/assets/19390499/24575903/33d9712a-16b2-11e7-9a73-b185b5876f4e.png">

how to reproduce:
Write a script to pull data every 1-3 seconds, and monitor for 1-2 minutes. 
the amount will jump with difference in 46k users up and back.

**Comment by shekenahglory** [comment]
cannot reproduce, assuming the issue was fixed. Reopen if you see it again.
