### ISSUE TITLE
i need sell/buy orders

### ISSUE THREAD

**Issue by mk148a** [ripple/rippled-historical-database#144]
Hi, i want to use sell and buyy orders,
https://data.ripple.com/v2/exchanges/XRP/BTC+rchGBxcD1A1C2tdxF6papQYZ8kjRKMYcL?limit=1000&descending=true its worked but i cant understand buy and sell order... Please help me

**Comment by shekenahglory** [comment]
the `provider` is the account that placed the initial offer, and the `taker` is the account that consumed the offer, so if the `taker` account is the `buyer` its a buy otherwise the `taker` is the `seller` and its a sell.
