### ISSUE TITLE
Unable to get payment history with descending true

### ISSUE THREAD

**Issue by greed0803** [ripple/rippled-historical-database#151]
Unable to get payment history with descending true

> https://data.ripple.com/v2/accounts/<account>/payments?type=received&limit=1000&start=2017-08-31T00:00:00Z&end=2017-08-31T23:59:59Z&descending=true

returns 

> {
  "result": "error",
  "message": "unable to retrieve payments"
}

**Comment by shekenahglory** [comment]
The URL here is invalid, but likely the query will work if you remove descending=true, probably the same issue as https://github.com/ripple/rippled-historical-database/issues/157

**Comment by 0x49D1** [comment]
Same here: https://data.ripple.com/v2/accounts/rnMCfd99pwRE8u4LxE43Z1pDzock2kXbLQ/transactions?type=Payment&result=tesSUCCESS&descending=true&limit=20 The query used to work and I was using it to get the latest transactions from time-to-time manually in cases, when we had to stop our rippled instance. Now the query works without `descending` filter, but that is useless for our case. Is this a bug? Or is there any other more correct way to, lets say, get 50 latest received transactions?

**Comment by shekenahglory** [comment]
Yes its a known bug in hbase with reverse scans, it won't be fixed in this version of the API, but the next version won't have the issue.  Until then, is it possible to use ascending with a limited range via start and end dates?
