### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by software-programmer** [ripple/rippled-historical-database#156]
I've been attempting to query account payments using the REST API at https://data,ripple.com, but using native HttpWebRequest in .Net causes an exception with the message "Could not create SSL/TLS secure channel".

I do not have this issue on https://api.altnet.rippletest.net:5990

Any pointers would be appreciated

**Comment by shekenahglory** [comment]
you've got a comma in the URL posted here...could that be the issue?

**Comment by software-programmer** [comment]
I've managed to work through the issue. 

The server is TLS1.2 and I believe .Net 4.5 defaults to Ssl 3.0 | Tls 1.0 | Tls 1.1

Using this code I can override the default `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`

.Net 4.6 defaults to Tls 1.0 | Tls 1.1 | Tls 1.2 I believe
