### ISSUE TITLE
Can't combine filters when querying payments

### ISSUE THREAD

**Issue by software-programmer** [ripple/rippled-historical-database#157]
I can [Filter Payments that are Type = Received](https://data.ripple.com/v2/accounts/rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B/payments?type=received)

and I can [Filter Payments by Descending = True](https://data.ripple.com/v2/accounts/rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B/payments?descending=true)

but I can't [Filter Payments that are Type = Received and Descending = True](https://data.ripple.com/v2/accounts/rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B/payments?type=received&descending=true)

Seems a little odd to me and the documentation doesn't seem to state I can't do this.

**Comment by shekenahglory** [comment]
This has to do with a bug in hbase on reverse scans.  it can happen any time its reversed, but will occur more frequently when filters are used. its best to avoid the reversed scan if you can.

**Comment by software-programmer** [comment]
If I need to find the latest 5 transactions, do I have to page through them all until I get to the end?

**Comment by shekenahglory** [comment]
yes, unfortunately. the issue occurs more on accounts like this with a large number of TX - and if you can limit the date range that is helpful.  Probably the next version of API will have descending only to address the issue, but this version won't be fixed unless we upgrade to a version of hbase that has addressed the issue.
