### ISSUE TITLE
Importing 

### ISSUE THREAD

**Issue by crackcomm** [ripple/rippled-historical-database#158]
Following classes are exported already constructed:

* [Client](https://github.com/ripple/rippled-historical-database/blob/develop/import/client.js#L53)
* [Importer](https://github.com/ripple/rippled-historical-database/blob/develop/lib/ripple-importer.js#L432)

Imported as classes:

* [import/live.js](https://github.com/ripple/rippled-historical-database/blob/develop/import/live.js#L4)

It causes issues on importing.

**Comment by crackcomm** [comment]
@shekenahglory should I submit a pull request?

**Comment by shekenahglory** [comment]
fixed https://github.com/ripple/rippled-historical-database/pull/162
