### ISSUE TITLE
Got error of YUM-UTILS

### ISSUE THREAD

**Issue by alexsubota** [ripple/rippled-historical-database#167]
Hi guys!
I try to install my own instance of the Historical Database software, but got error.

$ docker-compose build
hbase uses an image, skipping
Building webapp
Step 1/2 : FROM node:4.4-onbuild
# Executing 3 build triggers
 ---> Using cache
 ---> Using cache
 ---> Using cache
 ---> ec0b8eae9828
Step 2/2 : RUN bash scripts/versionsSetup.sh
 ---> Running in c1912ded68fb
: invalid optionSetup.sh: line 2: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
scripts/versionsSetup.sh: line 3: $'\r': command not found
scripts/versionsSetup.sh: line 13: syntax error: unexpected end of file
ERROR: Service 'webapp' failed to build: The command '/bin/sh -c bash scripts/versionsSetup.sh' returned a non-zero code: 2

How can i fix this?

**Comment by shekenahglory** [comment]
docker is only used for tests, you would not run it that way - and its not a particularly easy thing to maintain. ideally you need a storm server/cluster for importing XRP ledger data, and an hbase cluster set up first.  Then you can point the config to hbase, and run the data API with `node api/index.js`
