### ISSUE TITLE
HBASE-THRIFT account_offers thrift connection error: Error: read ECONNRESET undefined 

### ISSUE THREAD

**Issue by yangyang9966** [ripple/rippled-historical-database#168]
When i use the command " node import/live ", i meet  problem,as follow：
error: [2018-04-26 09:36:41.741] HBASE-THRIFT account_offers thrift connection error: Error: read ECONNRESET undefined .

**Comment by shekenahglory** [comment]
Either the config detailing the thrift connection is not correct, or the thrift server itself is not configured properly
