### ISSUE TITLE
error saving parsed data thrift connection error: Error: write EPIPE

### ISSUE THREAD

**Issue by yangyang9966** [ripple/rippled-historical-database#170]
i meet the problem , i  use  " node  import/live " command ,as follow:
info: [2018-04-27 07:55:06.952] IMPORTER [2018-04-27T07:55:06.952Z] Got ledger: 38252923 
info: [2018-04-27 07:55:06.997] HBASE-THRIFT test_account_offers - saving 23 rows 
info: [2018-04-27 07:55:07.006] HBASE-THRIFT test_balance_changes - saving 22 rows 
info: [2018-04-27 07:55:07.010] HBASE-THRIFT test_payments - saving 2 rows 
info: [2018-04-27 07:55:07.011] HBASE-THRIFT test_account_payments - saving 4 rows 
info: [2018-04-27 07:55:07.014] HBASE-THRIFT test_lu_affected_account_transactions - saving 34 rows 
info: [2018-04-27 07:55:07.016] HBASE-THRIFT test_lu_account_offers_by_sequence - saving 7 rows 
error: [2018-04-27 07:55:07.017] HBASE-THRIFT test_account_offers thrift connection error: Error: write EPIPE undefined 
error: [2018-04-27 07:55:07.017] HBASE-THRIFT test_balance_changes thrift connection error: Error: write EPIPE undefined 
error: [2018-04-27 07:55:07.018] HBASE-THRIFT test_payments thrift connection error: Error: write EPIPE undefined 
error: [2018-04-27 07:55:07.018] HBASE-THRIFT test_account_payments thrift connection error: Error: write EPIPE undefined 
error: [2018-04-27 07:55:07.018] HBASE-THRIFT test_lu_affected_account_transactions thrift connection error: Error: write EPIPE undefined 
error: [2018-04-27 07:55:07.018] HBASE-THRIFT test_lu_account_offers_by_sequence thrift connection error: Error: write EPIPE undefined 
error: [2018-04-27 07:55:07.018] HBASE-THRIFT error saving parsed data thrift connection error: Error: write EPIPE 
error: [2018-04-27 07:55:07.018] LIVE IMPORT unable to save parsed data for ledger: 38252923 

 why?

**Comment by BeBeMo** [comment]
Maybe you haven't start ThriftServer service.

**Comment by shekenahglory** [comment]
its some sort of issue with your thrift connection.
