### ISSUE TITLE
Rippled historical database hbase raw ledger data

### ISSUE THREAD

**Issue by offlinehacker** [ripple/rippled-historical-database#179]
We would kindly ask if it would be possible to get access to hbase raw ledger data, so we can import it into our own rippled historical db instance?

**Comment by shekenahglory** [comment]
what data are you looking for? all tables extracted from ledger and transaction data?

**Comment by offlinehacker** [comment]
I assume we would at least need ledger data, so we can backfill storm importer that would do other aggregations. Currently we are having issues, that some endpoints on ripple data API got deprecated, and we really need to run our own instance, as we are using some of this functionality. We are also in contact with Nik, and they will provide full rippled history, so that's also one way we can import from, but I don't know what is faster/easier?
