### ISSUE TITLE
Support for removing old entries from databases

### ISSUE THREAD

**Issue by offlinehacker** [ripple/rippled-historical-database#68]
So we are running our own instance of ripple historical database(currently on couchdb, for performance resaons), but we do not want to keep all historical entries, because of lack of free space. How should i integrate this feature. We need a solution asoap, i will hack something today to remove old entries from couchdb.

**Comment by shekenahglory** [comment]
We didn't implement anything like this, but my guess is all you need to do is set up a system to go through the documents (ledgers) and remove ones older than a certain date.  After that is done, you may have to run a compaction process to remove the corresponding view data - unless that is already automated.

**Comment by offlinehacker** [comment]
Actually i did that, but i had some problems. For some reason i managed to delete not only old, but also new entries in couchdb(shame on me). I assume that i have to use close_time_timestamp as date value? I used this snippet:

```
server = Server()
db = server['rippled']

time = datetime.datetime.utcnow() - datetime.timedelta(days=30)
ts = calendar.timegm(time.timetuple())
for doc in page(db, '_all_docs', 100):
    if doc.get('close_time_timestamp') < ts * 1000:
        db.purge(doc)

db.compact()
```

CPU for couchdb is still high for some reason, i guess it's still purging/compacting database?

**Comment by shekenahglory** [comment]
I think that would be right, make sure close_time_timestamp is unix time though, not ripple epoch time.  I think the compaction can take some time.

**Comment by offlinehacker** [comment]
Well it was, but we still lost all the data. It's so wierd, i will try to debug this.
