### ISSUE TITLE
How to make batch/bulk get rest api  calls 

### ISSUE THREAD

**Issue by t6166as** [ripple/rippled-historical-database#72]
Is there any way to get multiple transactions in one get call? If so, could anyone provide an example.

**Comment by shekenahglory** [comment]
There is not with v1 API, there will be however with v2 - hoping to release it shortly.  With v1, the best you can do is determine which ledgers contain the transactions you want, and use `v1/ledgers/{ledger index}?expand=true`

**Comment by shekenahglory** [comment]
https://data.ripple.com/v2/transactions?descending=true
https://ripple.com/build/data-api-v2/#get-transactions

**Comment by ran-eh** [comment]
I can't find it in the V2 docs - any pointers?
