### ISSUE TITLE
Getting check violation errors while backfill

### ISSUE THREAD

**Issue by t6166as** [ripple/rippled-historical-database#74]
I am getting bunch of check violation error and then backfill process stops.  Is there a way around ?  Should i make I script restart every 10 minutes ?  It complains about gap in ledgers and then stops.  I restart it and then it goes through couple of thousand transactions and then again stops.  I am trying to get historical information so that we could do economic analysis over transactions ( to compare ripple to our existing dataset of traditional transactions) and hence I need a large pool of transactions to go through.

**Comment by shekenahglory** [comment]
can you tell me what scripts/parameters you are using, and what error you are getting?

**Comment by t6166as** [comment]
abhi@ubuntu:~/ripple/rippled-historical-database$ node import/postgres/backfill

info: [2015-07-23 20:50:42.397] POSTGRES HISTORY ledger saved: 14807419 --- 1 of 1
info: [2015-07-23 20:50:42.397] POSTGRES HISTORY finding gaps - start:  14807419
info: [2015-07-23 20:50:42.397] POSTGRES HISTORY validating ledgers: 14807369 - 14807419
info: [2015-07-23 20:50:42.399] POSTGRES HISTORY missing ledger at: 14807419
info: [2015-07-23 20:50:42.399] POSTGRES HISTORY gap ends at: 14807418
info: [2015-07-23 20:50:42.585] POSTGRES Saving ledger: 14807419
error: [2015-07-23 20:50:42.641] POSTGRES Error saving ledger: { [error: new row for relation "transactions" violates check constraint "transactions_tx_result_check"]
  name: 'error',
  length: 628,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (\\x8a4f08c2bc3a71390452c18faeae21101c60030f9afe81deb6431215e9b0cf..., \\x120000220000000024000008e9201b00e1f17d61d4d1c37937e08000000000..., \\x201c00000007f8e51100612500e1f179550a2fbb809a3e59fc62cbb99791df..., \\x749efb3e86b0dda3bdae4be25360ac99bdbaeb28fdb9770a202225855621a8..., 14807419, 7, 1437642890, tecDST_TAG_NEEDED, Payment, \\x724252586b59594d786364345a6a6662364e394b7064364355475854524363..., 2281).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  file: 'execMain.c',
  line: '1659',
  routine: 'ExecConstraints' } 14807419
info: [2015-07-23 20:50:42.641] POSTGRES HISTORY ledger saved: 14807419 --- 1 of 1
info: [2015-07-23 20:50:42.641] POSTGRES HISTORY finding gaps - start:  14807419
info: [2015-07-23 20:50:42.641] POSTGRES HISTORY validating ledgers: 14807369 - 14807419
info: [2015-07-23 20:50:42.643] POSTGRES HISTORY missing ledger at: 14807419
info: [2015-07-23 20:50:42.643] POSTGRES HISTORY gap ends at: 14807418
info: [2015-07-23 20:50:42.817] POSTGRES Saving ledger: 14807419
error: [2015-07-23 20:50:42.842] POSTGRES Error saving ledger: { [error: new row for relation "transactions" violates check constraint "transactions_tx_result_check"]
  name: 'error',
  length: 628,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (\\x8a4f08c2bc3a71390452c18faeae21101c60030f9afe81deb6431215e9b0cf..., \\x120000220000000024000008e9201b00e1f17d61d4d1c37937e08000000000..., \\x201c00000007f8e51100612500e1f179550a2fbb809a3e59fc62cbb99791df..., \\x749efb3e86b0dda3bdae4be25360ac99bdbaeb28fdb9770a202225855621a8..., 14807419, 7, 1437642890, tecDST_TAG_NEEDED, Payment, \\x724252586b59594d786364345a6a6662364e394b7064364355475854524363..., 2281).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  file: 'execMain.c',
  line: '1659',
  routine: 'ExecConstraints' } 14807419
info: [2015-07-23 20:50:42.843] POSTGRES HISTORY ledger saved: 14807419 --- 1 of 1
info: [2015-07-23 20:50:42.843] POSTGRES HISTORY finding gaps - start:  14807419
info: [2015-07-23 20:50:42.843] POSTGRES HISTORY validating ledgers: 14807369 - 14807419
info: [2015-07-23 20:50:42.845] POSTGRES HISTORY missing ledger at: 14807419
info: [2015-07-23 20:50:42.845] POSTGRES HISTORY gap ends at: 14807418
info: [2015-07-23 20:50:43.020] POSTGRES Saving ledger: 14807419

**Comment by shekenahglory** [comment]
its failing because the enum on the 'transactions' table does not contain 'tecDST_TAG_NEEDED'  - it should if you are using the latest version: https://github.com/ripple/rippled-historical-database/blob/develop/migrations/20140915173225_initial.js#L54 - but I did notice that the same enum on the account_transactions table did not have this result type - which resulted in a similar error.  I updated the code to include this tx_result type in both tables, so you'll need to get the latest and update your postgres schema.  

one way to do that is run:
`./node_modules/knex/lib/bin/cli.js migrate:rollback`
then
`./node_modules/knex/lib/bin/cli.js migrate:latest`

but you will lose all your data accumulated so far doing that.  There is probably another way to update the enums on the postgres schema but I don't know it off hand.

**Comment by t6166as** [comment]
So we just need to update the constraints on the tables and it should work.  Something like this....

 alter table transactions drop constraint transactions_tx_result_check;
alter table transactions add constraint transactions_tx_result_check 
CHECK
(tx_result = 
ANY (ARRAY['tesSUCCESS'::text, 
'tecCLAIM'::text, 
'tecPATH_PARTIAL'::text, 
'tecUNFUNDED_ADD'::text, 
'tecUNFUNDED_OFFER'::text, 
'tecUNFUNDED_PAYMENT'::text, 
'tecFAILED_PROCESSING'::text, 
'tecDST_TAG_NEEDED'::text,
'tecDIR_FULL'::text, 'tecINSUF_RESERVE_LINE'::text, 'tecINSUF_RESERVE_OFFER'::text, 'tecNO_DST'::text, 
'tecNO_DST_INSUF_XRP'::text, 'tecNO_LINE_INSUF_RESERVE'::text, 'tecNO_LINE_REDUNDANT'::text, 
'tecPATH_DRY'::text, 'tecUNFUNDED'::text, 'tecMASTER_DISABLED'::text, 'tecNO_REGULAR_KEY'::text, 'tecOWNERS'::text, 'tecNO_ISSUER'::text, 'tecNO_AUTH'::text, 'tecNO_LINE'::text, 'tecINSUFF_FEE'::text, 'tecFROZEN'::text, 'tecNO_TARGET'::text, 'tecNO_PERMISSION'::text, 'tecNO_ENTRY'::text, 'tecINSUFFICIENT_RESERVE'::text]));

 alter table account_transactions drop constraint account_transactions_tx_result_check;
 
 alter table account_transactions add constraint account_transactions_tx_result_check 
CHECK
(tx_result = 
ANY (ARRAY['tesSUCCESS'::text, 
'tecCLAIM'::text, 
'tecPATH_PARTIAL'::text, 
'tecUNFUNDED_ADD'::text, 
'tecUNFUNDED_OFFER'::text, 
'tecUNFUNDED_PAYMENT'::text, 
'tecFAILED_PROCESSING'::text, 
'tecDST_TAG_NEEDED'::text,
'tecDIR_FULL'::text, 'tecINSUF_RESERVE_LINE'::text, 'tecINSUF_RESERVE_OFFER'::text, 'tecNO_DST'::text, 
'tecNO_DST_INSUF_XRP'::text, 'tecNO_LINE_INSUF_RESERVE'::text, 'tecNO_LINE_REDUNDANT'::text, 
'tecPATH_DRY'::text, 'tecUNFUNDED'::text, 'tecMASTER_DISABLED'::text, 'tecNO_REGULAR_KEY'::text, 'tecOWNERS'::text, 'tecNO_ISSUER'::text, 'tecNO_AUTH'::text, 'tecNO_LINE'::text, 'tecINSUFF_FEE'::text, 'tecFROZEN'::text, 'tecNO_TARGET'::text, 'tecNO_PERMISSION'::text, 'tecNO_ENTRY'::text, 'tecINSUFFICIENT_RESERVE'::text]));

**Comment by t6166as** [comment]
This is better version

 alter table transactions drop constraint transactions_tx_result_check;
alter table transactions add constraint transactions_tx_result_check 
CHECK
(tx_result = 
ANY (ARRAY['tesSUCCESS',
        'tecCLAIM',
        'tecPATH_PARTIAL',
        'tecUNFUNDED_ADD',
        'tecUNFUNDED_OFFER',
        'tecUNFUNDED_PAYMENT',
        'tecFAILED_PROCESSING',
        'tecDIR_FULL',
        'tecINSUF_RESERVE_LINE',
        'tecINSUF_RESERVE_OFFER',
        'tecNO_DST',
        'tecNO_DST_INSUF_XRP',
        'tecNO_LINE_INSUF_RESERVE',
        'tecNO_LINE_REDUNDANT',
        'tecPATH_DRY',
        'tecUNFUNDED',
        'tecMASTER_DISABLED',
        'tecNO_REGULAR_KEY',
        'tecOWNERS',
        'tecNO_ISSUER',
        'tecNO_AUTH',
        'tecNO_LINE',
        'tecINSUFF_FEE',
        'tecFROZEN',
        'tecNO_TARGET',
        'tecNO_PERMISSION',
        'tecNO_ENTRY',
        'tecINSUFFICIENT_RESERVE',
        'tecNEED_MASTER_KEY',
        'tecDST_TAG_NEEDED',
        'tecINTERNAL']));

 alter table account_transactions drop constraint account_transactions_tx_result_check;
 
 alter table account_transactions add constraint account_transactions_tx_result_check 
 CHECK
(tx_result = 
ANY (ARRAY['tesSUCCESS',
        'tecCLAIM',
        'tecPATH_PARTIAL',
        'tecUNFUNDED_ADD',
        'tecUNFUNDED_OFFER',
        'tecUNFUNDED_PAYMENT',
        'tecFAILED_PROCESSING',
        'tecDIR_FULL',
        'tecINSUF_RESERVE_LINE',
        'tecINSUF_RESERVE_OFFER',
        'tecNO_DST',
        'tecNO_DST_INSUF_XRP',
        'tecNO_LINE_INSUF_RESERVE',
        'tecNO_LINE_REDUNDANT',
        'tecPATH_DRY',
        'tecUNFUNDED',
        'tecMASTER_DISABLED',
        'tecNO_REGULAR_KEY',
        'tecOWNERS',
        'tecNO_ISSUER',
        'tecNO_AUTH',
        'tecNO_LINE',
        'tecINSUFF_FEE',
        'tecFROZEN',
        'tecNO_TARGET',
        'tecNO_PERMISSION',
        'tecNO_ENTRY',
        'tecINSUFFICIENT_RESERVE',
        'tecNEED_MASTER_KEY',
        'tecDST_TAG_NEEDED',
        'tecINTERNAL']));

**Comment by shekenahglory** [comment]
yes that should do it - I also changed the code slightly to exit the process when it gets an error, instead of looping on it

**Comment by t6166as** [comment]
The only problem is face is this one

info: [2015-07-24 00:59:21.789] POSTGRES HISTORY validating ledgers: 14817806 - 14817856
info: [2015-07-24 00:59:21.794] POSTGRES HISTORY validating ledgers: 14817756 - 14817806
info: [2015-07-24 00:59:21.799] POSTGRES HISTORY validating ledgers: 14817706 - 14817756
info: [2015-07-24 00:59:21.872] POSTGRES HISTORY incorrect ledger hash at: 14817752
error: [2015-07-24 00:59:22.204] IMPORTER expected different parent hash: 14817752

**Comment by shekenahglory** [comment]
Yes this is not an issue with the code, its working correctly, for some reason the client handlers are returning an unvalidated ledger for 14817752 - talking to the rippled team about it.  If you can, just skip that one for now.

**Comment by shekenahglory** [comment]
fixed now.  You probably have to delete the incorrect ledger from your db (you could use this: https://github.com/ripple/rippled-historical-database/tree/develop/scripts) - I've updated the code so it should not be able to import an unvalidated ledger in the future.

**Comment by t6166as** [comment]
Awesome !! thank you so much.  By the way, how do you recommend I should go about getting details of a given transaction ( like USD, JPY, Amount). Should I loop all tx_hash and get it from REST API calls  to get json format or should I try to decode the tx binary format?
