### ISSUE TITLE
Best method to get all details of a given transaction

### ISSUE THREAD

**Issue by t6166as** [ripple/rippled-historical-database#78]
I am looking for a method to get all details for a given transactions. I can make REST API call to get JSON output but is that the right way to do it with entire history of ledgers?

**Comment by shekenahglory** [comment]
All the data that you need is stored in the postgres DB, but it is stored as binary via custom serialization.  To get the raw transaction details and the transaction metadata, you'll have to encode the tx_raw and tx_meta fields as hex when you retrieve it from the DB (https://github.com/ripple/rippled-historical-database/blob/develop/api/lib/db.js#L56-L62) and then use ripple-lib to convert the hex to JSON (https://github.com/ripple/rippled-historical-database/blob/develop/api/lib/db.js#L81-L82)
