### ISSUE TITLE
Consider using extracted Quality field for rate field

### ISSUE THREAD

**Issue by donovanhide** [ripple/rippled-historical-database#82]
Here are some example exchanges for small amounts where the rate field is wildly out of kilter with the surrounding trades:

https://gist.github.com/donovanhide/fa79455714eba7980a20

When the traded amounts are very small, the calculated rate will tend to be subject to the effects of the rounding of the traded amounts. I would suggest extracting the last 8 bytes (16 hex digits) from the BookDirectory field for the Modified or Deleted Offer and doing the crazy Quality/ExchangeRate derivation dance to get the actual rate that the original offer was placed at. Effectively the reverse of this:

https://github.com/ripple/rippled/blob/5ec3534feaf68b5a377e1642a671bd708a032995/src/ripple/protocol/impl/STAmount.cpp#L370-L371

**Comment by shekenahglory** [comment]
Yeah, I am actually using it - the ones originating from the 'payment'
transactions is the result of a known bug in the payment logic with very
small leftover amounts :(  apparently its a lot of work to fix, and they
were going to rewrite that whole bit at some point.  This should not affect
the offer create ones though, so I will have to look into those.  There is
a ripple-lib function for getting the rate from the BookDirectory.
