### ISSUE TITLE
Inconsistent formatting of timestamps

### ISSUE THREAD

**Issue by matejr** [ripple/rippled-historical-database#89]
According to

https://ripple.com/build/data-api-v2/#timestamps

timestamps should include time zones (Z or +0:00), but currently timestamps returned from Data API v2 don't include them. This change breaks some applications.

For example,

https://data.ripple.com/v2/exchanges/XRP/USD+rMwjYedjc7qqtKYVLiAccJSmCwih4LnE2q?limit=200&interval=1day&format=csv

currently returns timestamps without time zones. But several days ago similar file included time zones:

https://gist.github.com/matejr/692a7bd0b5f42ef4d64f

Timestamps currently also include seconds, although this is not specified in

https://ripple.com/build/data-api-v2/#timestamps

**Comment by shekenahglory** [comment]
fixed in v2.0.4 https://github.com/ripple/rippled-historical-database/commit/76cb9a5898d77c98794f100caa02e80b58a84cd6
