### ISSUE TITLE
unable to see XRP in ledgers 

### ISSUE THREAD

**Issue by t6166as** [ripple/rippled-historical-database#91]
I downloaded ledgers but could not find any instance of XRP as currency.   Is that an issue with the data or we are missing XRP?

**Comment by shekenahglory** [comment]
If you are looking at raw ledgers, XRP values are defined differently than other currencies - for all other currencies, you will see a JSON object with value, currency, and issuer.  for XRP, it will instead be an integer that represents XRP as drops (.0000001).  so when you see an integer value, its XRP and dividing by 1000000 will give you the amount in XRP
