### ISSUE TITLE
Include memo and invoiceid in /v2/accounts/account/payments

### ISSUE THREAD

**Issue by offlinehacker** [ripple/rippled-historical-database#93]
When we are paginating transactions while processing them, we would need these fields to be a able to process transactions without additional requests.

**Comment by shekenahglory** [comment]
we are not actually storing that data in the optimized payments table - it would probably make sense to store invoiceid, but I'm not sure it would make sense to store memos - would it be reasonable for you to use the `/v2/accounts/account/transactions` endpoint instead, with `?type=Payment`

**Comment by offlinehacker** [comment]
Well, `/v2/accounts/account/transactions` can't filter on inbound payment transactions.

**Comment by offlinehacker** [comment]
invoiceid would be sufficient

**Comment by shekenahglory** [comment]
invoice id is there now, going forward:
https://data.ripple.com/v2/accounts/rBXVfXi5eVZ2W1khFe812c7s7EnPfBkrAn/payments?start=2016-01-22T00:00&limit=1

it will take a bit longer to get history backfilled.
https://github.com/ripple/rippled-historical-database/commit/f82d158f0786a24294f18b6345bf75961df785f1

**Comment by offlinehacker** [comment]
Thanks!
